### PR TITLE
fix(otg_v2): correct UEP_DMA bit_size from 16 to 32

### PR DESCRIPTION
**Pull request by Dummyc0m**
Fix applied according to the datasheet.

### CODE REVIEW

**Comment by andelf** [comment]
Could you provide the source of the change? According to the RM doc:

image
image

**Comment by Codetector1374** [comment]
😮‍💨 Sigh.... WCH documentation is inconsistent at best...

This is from `CH32FV2x_3xRM.pdf`

Screenshot 2024-09-15 at 10 59 45 AM

The address map also agrees with this, each of the DMA register are spaced 4 apart:

Screenshot 2024-09-15 at 11 01 48 AM

Logically it also makes sense, since we are expected to fill a memory address into there, which would be 32 bits.

The register name on my manual seems to be R32 indicating it is a 32bit register.

**Comment by Codetector1374** [comment]
@andelf  if you get a chance to take a look at this would be extremely helpful :)

**Comment by andelf** [comment]
Thanks! I'll check the EVT source code for these registers.

**Comment by Codetector1374** [comment]
perfect. We checked they seems to cast to uint32_t as well but feel free to double check

**Review by andelf — APPROVED** [review]

**Comment by andelf** [comment]
Let's get this merged.

**Pull request merged**
